services:
  db:
    image: postgres:17.2
    container_name: recipe_db
    environment:
      - POSTGRES_USER=user_name
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
    ports:
      - "5433:5432"
    volumes:
      - ./db_folder:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_name -d db_name"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: recipe_api
    ports:
      - "8011:8000"
    
    command: > 
      bash -c 
      "alembic upgrade head && python app/main.py"
    environment:
      - DB_URL=postgresql://user_name:password@db:5432/db_name
    depends_on:
      db:
        condition: service_healthy


volumes:
  db_folder: